headYaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: headYaw
    joint_speed: 20

    motor:
        id: 123
        init: 512
        min: 324
        max: 700

headPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: headPitch
    joint_speed: 20

    motor:
        id: 122
        init: 650
        min: 512
        max: 700

rightshoulderYawm_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightshoulderYawm
    joint_speed: 10

    motor:
        id: 111
        init: 2726
        min: 1600
        max: 3000

rightshoulderPitchm_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightshoulderPitchm
    joint_speed: 5

    motor:
        id: 113
        init: 3400
        min: 2000
        max: 3750

rightshoulderRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightshoulderRoll
    joint_speed: 20
    motor:
        id: 115
        init: 1086
        min: 5
        max: 1300

rightelbowPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightelbowPitch
    joint_speed: 20
    motor:
        id: 116
        init: 1630
        min: 1625
        max: 2600

rightelbowRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightelbowRoll
    joint_speed: 20
    motor:
        id: 117
        init: 1783
        min: 280
        max: 2860

rightwristPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightwristPitch
    joint_speed: 20
    motor:
        id: 118
        init: 2427
        min: 1900
        max: 3370

rightwristRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightwristRoll
    joint_speed: 20
    motor:
        id: 119
        init: 2452
        min: 1810
        max: 2750
        
rightgripper_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightgripper
    joint_speed: 20
    motor:
        id: 120
        init: 1840
        min: 1610
        max: 1840
        
 
leftshoulderYawm_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftshoulderYawm
    joint_speed: 10

    motor:
        id: 101
        init: 1300
        min: 1300
        max: 3072

leftshoulderPitchm_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftshoulderPitchm
    joint_speed: 10

    motor:
        id: 103
        init: 2900
        min: 1500
        max: 3100

leftshoulderRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftshoulderRoll
    joint_speed: 10
    motor:
        id: 105
        init: 2364
        min: 1400
        max: 3000

leftelbowPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftelbowPitch
    joint_speed: 10
    motor:
        id: 106
        init: 2600
        min: 1700
        max: 3000

leftelbowRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftelbowRoll
    joint_speed: 10
    motor:
        id: 107
        init: 512
        min: 0
        max: 1024

leftwristPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftwristPitch
    joint_speed: 10
    motor:
        id: 108
        init: 1690
        min: 700
        max: 2700

leftwristRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftwristRoll
    joint_speed: 10
    motor:
        id: 109
        init: 512
        min: 300
        max: 560
        
leftgripper_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftgripper
    joint_speed: 10
    motor:
        id: 110
        init: 260
        min: 260
        max: 415

